"""BitVectorProtocol definition.

This module defines the typing protocol for BitVector operations,
ensuring type safety and consistent interfaces.
"""

from typing import Any, Iterator, Protocol, Self


class BitVectorProtocol(Protocol):
    """Protocol defining the structural typing interface for BitVector instances.

    Attributes:
        size: Total number of bits in the vector.
    """

    size: int

    def __xor__(self, other: Self) -> Self: ...
    def __and__(self, other: Self) -> Self: ...
    def __or__(self, other: Self) -> Self: ...
    def __invert__(self) -> Self: ...
    def __add__(self, other: Self) -> Self: ...
    def __iadd__(self, other: Self) -> Self: ...
    def __lshift__(self, n: int) -> Self: ...
    def __rshift__(self, n: int) -> Self: ...
    def __getitem__(self, pos: int | slice | Any) -> Any: ...
    def __setitem__(self, pos: int | slice | Any, item: int | Self | Any) -> Any: ...
    def __len__(self) -> int: ...
    def __int__(self) -> int: ...
    def __iter__(self) -> Iterator[int]: ...
    def __reversed__(self) -> Iterator[int]: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __le__(self, other: object) -> bool: ...
    def __gt__(self, other: object) -> bool: ...
    def __ge__(self, other: object) -> bool: ...
    def __contains__(self, otherBitVec: Self) -> bool: ...
    def bit_count(self) -> int: ...
    def count_bits_sparse(self) -> int: ...
    def next_set_bit(self, from_index: int = 0) -> int: ...
    def is_power_of_2(self) -> bool: ...
    def is_power_of_2_sparse(self) -> bool: ...
